language: python

os: linux
dist: bionic

before_install: python3 -m pip install -r test/requirements.txt
install: python3 -m pip install .

stages:
  - pylint
  - pip-install
  - pytest

jobs:
  include:
    - stage: pylint
      name: "Pylint check"
      install: skip
      script: python3 -m pylint opengrid/library/*.py --rcfile pylint.ini --exit-zero
      python: "3.8"

    - stage: pip-install
      name: "Local pip install"
      script: skip
      python: "3.8"

    - stage: pytest
      name: "Pytest Python 3.6"
      script: python3 -m pytest
      python: "3.6"

    - stage: pytest
      name: "Pytest Python 3.7"
      script: python3 -m pytest
      python: "3.7"

    - stage: pytest
      name: "Pytest Python 3.8"
      script: python3 -m pytest
      python: "3.8"

after_success:
  - COVERALLS_REPO_TOKEN="RbnaxzEouDqGe0oNVwEP4TBS0sL20ZpGg" coveralls
